- type: job
  parent: CMJobXenoBase
  id: CMXenoDefender
  name: cm-job-name-xeno-defender
  playTimeTracker: CMJobXenoDefender
  minimapIcon:
    sprite: _RMC14/Interface/map_blips.rsi
    state: defender

- type: playTimeTracker
  id: CMJobXenoDefender
