- type: job
  parent: CMJobXenoBase
  id: CMXenoWarrior
  name: cm-job-name-xeno-warrior
  playTimeTracker: CMJobXenoWarrior
  minimapIcon:
    sprite: _RMC14/Interface/map_blips.rsi
    state: warrior

- type: playTimeTracker
  id: CMJobXenoWarrior
